# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPreview():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(20)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_preview(self):
    self.driver.get("http://localhost:3300/")
    self.driver.set_window_size(1051, 608)
    self.driver.find_element(By.CSS_SELECTOR, ".el-col:nth-child(3) .el-link--inner").click()
  
