# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

class TestSearch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.driver.implicitly_wait(20)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_search(self):
    self.driver.get("http://localhost:3300/")
    self.driver.set_window_size(1047, 605)
    self.driver.find_element(By.CSS_SELECTOR, ".main-icon-container:nth-child(2) > .l-icon").click()
    WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.XPATH, '/html/body/div[1]/div/div[1]/nav/div/nav[2]/div[1]/div[2]/div/input'))).click()
    WebDriverWait(self.driver, 10).until(EC.presence_of_element_located(
      (By.XPATH, '/html/body/div[1]/div/div[1]/nav/div/nav[2]/div[1]/div[2]/div/input'))).send_keys("container")
    WebDriverWait(self.driver, 10).until(EC.presence_of_element_located((By.XPATH, '/html/body/div[27]/div[1]/div/div[1]/ul/li'))).click()
    # self.driver.find_element(By.CSS_SELECTOR, ".el-input--small > .el-input__inner").click()
    # self.driver.find_element(By.CSS_SELECTOR, ".el-input--small > .el-input__inner").send_keys("container")
    # self.driver.find_element(By.ID, "el-autocomplete-3295-item-0").click()
  
